#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume
url: 'http://webjeda.com'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: Software Engineer with 5+ years of experience delivering high-performance and secure web solutions. Driven by a passion for innovation, I tackle daily coding challenges to sharpen my skills and stay at the forefront of emerging technologies. My expertise lies in developing efficient and scalable solutions that seamlessly integrate functionality and security. Whether collaborating with cross-functional teams or leading projects, I am committed to exceeding expectations and driving innovation in every endeavor.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: cnabil # blue turquoise green berry orange ceramic teal oceanstale
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false